name: Node CI

on:
  push:
    branches:
      - '**'

jobs:
  lint:
    name: Typecheck and Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install meteor
      run: curl "https://install.meteor.com/?release=1.11.1" | sh
    - name: restore node_modules
      uses: actions/cache@v2
      with:
        path: |
          meteor/node_modules
        key: ${{ runner.os }}-${{ hashFiles('meteor/package-lock.json') }}
    - name: Run typecheck and linter
      run: |
        cd meteor
        meteor npm install
        meteor npm run ci:lint
      env:
        CI: true
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install meteor
      run: curl "https://install.meteor.com/?release=1.11.1" | sh
    - name: restore node_modules
      uses: actions/cache@v2
      with:
        path: |
          meteor/node_modules
        key: ${{ runner.os }}-${{ hashFiles('meteor/package-lock.json') }}
    - name: Run typecheck and linter
      run: |
        cd meteor
        meteor npm install
        meteor npm run prepareForTest
        meteor npm run ci
      env:
        CI: true