name: Node CI

on:
  push:
    branches:
      - '**'

jobs:
  lint:
    name: Typecheck and Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # - name: Use Node.js ${{ matrix.node-version }}
    #   uses: actions/setup-node@v1
    #   with:
    #     node-version: ${{ matrix.node-version }}
    - name: Install meteor
      run: curl "https://install.meteor.com/?release=1.11.1" | sh
    - name: yarn install, build, and test
      run: |
        cd meteor
        meteor npm install
        meteor npm run ci:lint
      env:
        CI: true